name: ublue-hyprland
base-container: ghcr.io/ublue-os/base-main
fedora-version: 38
description: My own personal hyprland image! Download at your own risk! https://ublue.it/making-your-own/
rpms:
  - hyprland
  - waybar-hyprland
  - xdg-desktop-portal-hyprland
  - xorg-x11-server-Xwayland
  - swaybg
  - swayidle
  - swaylock
  - polkit-gnome
  - libseat
  - network-manager-applet
  - system-config-printer
  - firewall-config
  - blueman
  - libnotify
  - thunar
  - thunar-archive-plugin
  - thunar-volman
  - htop
  - imv
  - zathura
  - kvantum
  - qt5ct
  - qt6ct
  - gtk-murrine-engine
  - fastfetch
  - mpv
  - gparted
  - pavucontrol
  - dunst
  - yt-dlp
  - xarchiver
  - xdg-user-dirs
  - xdg-tools
  - greetd
  - greetd-selinux
  # launchers
  - fuzzel
  # terminals
  - foot
  # text editor
  - lite-xl
  # yafti deps
  - python3-pip
  - libadwaita
  # virtualisation
  #  - virt-install
  #  - virt-manager
  #  - virt-viewer
  #  - libvirt-client
  # - libvirt-daemon-kvm
  # screenshotting 
  - grimshot
  - wf-recorder
  # sway used to display login greeter, then exit
  #  - sway
  #  - sddm
  - wdisplays
  - ksshaskpass
  - kwalletmanager5
  # fonts
  - overpass-fonts
  - overpass-mono-fonts
  # dependencies for eww config:
  - ripgrep
  - light
  - socat
  - fish
  # general audio shit
  - sox
  - pactl
  # android shiz
  - android-file-transfer
  - android-tools
flatpaks:
  - org.freedesktop.Platform.ffmpeg-full/x86_64/22.08
  - com.github.tchx84.Flatseal/x86_64/stable
  - com.brave.Browser/x86_64/stable
  - org.fedoraproject.MediaWriter/x86_64/stable
  - org.kde.KStyle.Kvantum/x86_64/5.15-22.08
  - com.github.GradienceTeam/x86_64/stable
  - com.obsproject.Studio/x86_64/stable


