#!/bin/bash

volicons=("" "" "")
vol() {
  wpctl get-volume @DEFAULT_AUDIO_"$1"@ | awk '{print int($2*100)}'
}
ismuted() {
  wpctl get-volume @DEFAULT_AUDIO_"$1"@
  echo "true"?
}

  # initial values
  lvl=$(awk -v n="$(vol "SINK")" 'BEGIN{print int(n/34)}')
  ismuted=$(ismuted "SINK")

  if [ "$ismuted" = 1 ]; then
  	icon="${volicons[$lvl]}"
  else
    icon=""
  fi
  audio=1
  if [ "$(wpctl status | grep 'MUTED')" == "" ]; then
    audio=1
  else 
    audio=0
  fi

  echo '{"icon":"'"$icon"'","audio":"'"$audio"'","percent":"'"$(vol "SINK")"'","microphone":"'"$(vol "SOURCE")"'"}'


  # event loop
  pactl subscribe | rg --line-buffered "on sink" | while read -r _; do
    ismuted=$(ismuted "SINK")


    audio=1
    if [ "$(wpctl status | grep 'MUTED')" == "" ]; then
      audio=1
    else 
      audio=0
    fi

    echo '{"icon":"'"$icon"'","audio":"'"$audio"'","percent":"'"$(vol "SINK")"'","microphone":"'"$(vol "SOURCE")"'"}'
  done
fi
